### ISSUE TITLE
Twin ID filter work no correctly 

### ISSUE THREAD

**Issue by VenyaPanou** [threefoldtecharchive/tfgrid_dashboard#29]
https://explorer.test.grid.tf/farms
https://explorer.dev.grid.tf/farms
![Peek 2022-06-04 14-42](https://user-images.githubusercontent.com/106578096/171997475-62d85f99-bfcb-4504-aa1c-8364dc8d6df4.gif)

No.191 - Test case: TC271

**Comment by rkhamis** [comment]
@MohamedElmdary please verify this is fixed

**Comment by dmitri-alleo** [comment]
When searching for the records which exist, it seems to work correctly now,
but if nothing is found in the resources, it still shows a bunch of items instead of the empty field,
also if trying the Farm ID 10 and having Farm ID and Name in the filters, it mostly shows the correct results, but sometimes shows a bunch of items again
Generally works, but should there are moments when the results are not filtered correctly still

**Comment by mohamedamer453** [comment]
This is the same issue that happens [here](https://github.com/threefoldtech/tfgrid_dashboard/issues/28) and it's related to the filtering in the farms page not to a certain filter.

closing this one since it's a duplicate and it will be followed in https://github.com/threefoldtech/tfgrid_dashboard/issues/28
