### ISSUE TITLE
transfer section, the balance field has an issue.

### ISSUE THREAD

**Issue by Mahmoud-Emad** [threefoldtecharchive/tfgrid_dashboard#467]
I'm trying to transfer some `TFT's` to another account but got this error `Amount cannot exceed balance` while I have a lot of `TFT's`, also the balance card disappears when changing the tab from the sidebar.

[balance_issue.webm](https://user-images.githubusercontent.com/57001890/213909129-7e7cc420-eaaa-454e-a8ff-d2038af55ae3.webm)

I think it's related to [this issue](https://github.com/threefoldtech/tfgrid_dashboard/issues/464) also

**Comment by Mahmoud-Emad** [comment]
Should be fixed in https://github.com/threefoldtech/tfgrid_dashboard/pull/472

**Comment by zaelgohary** [comment]
The issue is not yet fixed on development as per the video below.

[transfer_issue.webm](https://user-images.githubusercontent.com/40770501/214069608-dbac2d81-81b7-40b1-b9b9-f9190387e135.webm)

**Comment by zaelgohary** [comment]
Verfied. Should be fixed in https://github.com/threefoldtech/tfgrid_dashboard/issues/464
