### ISSUE TITLE
TF Explorer input validation

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtecharchive/tfgrid_dashboard#96]
Tested on https://explorer.dev.grid.tf

All the fields in the filters for the nodes and farms have these problems.

### Numeric fields 

For the fields that should accept numeric values only like (Node ID, Farm ID, Twin ID, etc...) the user can enter negative values.

![image](https://user-images.githubusercontent.com/101194226/163168552-2b5a5253-9a17-4e92-a60b-7b50eccf834e.png)

### Textual fields

For the fields that should accept textual values like (Country Full Name, Farming Policy, etc...) the user can enter numeric values and special characters.

![image](https://user-images.githubusercontent.com/101194226/163169204-ea0ba64c-35aa-45a1-93c8-ba7dcb7d0479.png)

### Sliders

Also the sliders for the (CRU, HRU, MRU ,SRU) accept negative values.

![image](https://user-images.githubusercontent.com/101194226/163169690-d28935f3-e8f4-4b57-b2f8-72e6e0dcd9e4.png)

**Comment by mohamedamer453** [comment]
The issue is still available in the dashboard and these filed are still accepting non numeric values.

and the same issue is available in the `Free Public IP` filter

![image](https://user-images.githubusercontent.com/101194226/177814866-9fc2df80-9034-488a-b5ce-924060ecf335.png)

![image](https://user-images.githubusercontent.com/101194226/177814929-5bd7cfef-4faf-4849-841d-426a175d69f7.png)

**Comment by Mahmoud-Emad** [comment]
Numeric fields validation is fixed.

still working on the other field's validation.

**Comment by Mahmoud-Emad** [comment]
Textual fields, Free Public IP validation is fixed.

still working on Sliders.

**Comment by Mahmoud-Emad** [comment]
@mohamedamer453

Should all be fixed now, please test it carefully and let me know if there is an issue still out of case

**Comment by Mahmoud-Emad** [comment]
`Farm filter inputs` validations are fixed now, I'll open a PR request and move this issue from in progress to verification status.

PR opened here and waiting for review [117 - Development tfexplorer input validation](https://github.com/threefoldtech/tfgrid_dashboard/pull/117)

**Comment by mohamedamer453** [comment]
Verified.

### Numeric Fields

- For the numeric fields a new validation message was added when  the user enters a negative value or an invalid value like normal characters or special characters.

   ![image](https://user-images.githubusercontent.com/101194226/181488060-8bf4c065-748b-4b15-a2f4-82b8b7558327.png)

   ![image](https://user-images.githubusercontent.com/101194226/181488156-a403e7fc-083e-4374-928b-d63af0007637.png)


### Textual Fields

- For Textual fields a new validation message was added when the user enters any special character.

   ![image](https://user-images.githubusercontent.com/101194226/181488733-0ae46c08-0d21-4d4e-ae8c-2534becf8726.png)


### Sliders

- A new validation message was added to the slider input (CRU, MRU, HRU, SRU) when the user enters a negative value.

   ![image](https://user-images.githubusercontent.com/101194226/181487375-e8fc5fb4-bb7f-4117-9150-07f4dec72eb5.png)


### Free Public IP Filter

- New validation messages for the `Free Public IP` filter were added when the user enters a negative value or special characters.

   ![image](https://user-images.githubusercontent.com/101194226/181489305-cb4ab67e-8570-4940-bdbd-d33e2f5ded4b.png)

   ![image](https://user-images.githubusercontent.com/101194226/181489476-748eb628-1be4-4052-92f4-01e6e4d46760.png)

**Comment by mohamedamer453** [comment]
The only validations that's still missing is the message for numeric inputs in text fields

![image](https://user-images.githubusercontent.com/101194226/181489873-ca05f7b0-7ff2-4ce9-99a8-e16e54935e94.png)

**Comment by mohamedamer453** [comment]
Verified

The message for numeric inputs was added

![image](https://user-images.githubusercontent.com/101194226/181520457-aa8b0fc1-2d84-43df-aa5b-5187bf8807e4.png)

![image](https://user-images.githubusercontent.com/101194226/181520369-5d981734-de88-4b91-94fa-c7b07f22e263.png)
